services:
  user-db:
    image: postgres:17.6
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

  book-db:
    image: postgres:17.6
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books
    ports:
      - "5434:5432"
    volumes:
      - book_data:/var/lib/postgresql/data

  order-db:
    image: postgres:17.6
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - "5435:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    ports:
      - "8001:8000"
    depends_on:
      - user-db

  book-service:
    build: ./book-service
    ports:
      - "8002:8000"
    depends_on:
      - book-db

  order-service:
    build: ./order-service
    ports:
      - "8003:8000"
    depends_on:
      - order-db
      - book-service
      - user-service

  payment-service:
    build: ./payment-service
    ports:
      - "8004:8000"
    depends_on:
      - order-service

  notification-service:
    build: ./notification-service
    ports:
      - "8005:8000"

volumes:
  user_data:
  book_data:
  order_data:
