services:
  rabbitmq:
    image: rabbitmq:4.1.3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"   # broker
      - "15672:15672" # web dashboard

  user-db:
    image: postgres:17.6
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
      PGPORT: 5433
    ports:
      - "5433:5433"
    volumes:
      - user_data:/var/lib/postgresql/data

  book-db:
    image: postgres:17.6
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books
      PGPORT: 5434
    ports:
      - "5434:5434"
    volumes:
      - book_data:/var/lib/postgresql/data

  order-db:
    image: postgres:17.6
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
      PGPORT: 5435
    ports:
      - "5435:5435"
    volumes:
      - order_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    depends_on:
      - user-db

  book-service:
    build: ./book-service
    ports:
      - "8002:8002"
    depends_on:
      - book-db

  order-service:
    build: ./order-service
    ports:
      - "8003:8003"
    depends_on:
      - order-db
      - book-service
      - user-service
      - rabbitmq

  payment-service:
    build: ./payment-service
    depends_on:
      - rabbitmq

  notification-service:
    build: ./notification-service
    depends_on:
      - rabbitmq
  
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - book-service
      - order-service
      - payment-service
      - notification-service

volumes:
  user_data:
  book_data:
  order_data:
