FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o log-service ./cmd

FROM alpine:3.22.1
WORKDIR /root/
COPY --from=builder /app/log-service .

EXPOSE 9000
CMD ["./log-service"]
